return {
	{
		"IogaMaster/neocord",
		--"hitoyaCute/neocord",
		event = "VeryLazy",
		opts = {
			logo = "https://icons.iconarchive.com/icons/papirus-team/papirus-apps/512/nvim-icon.png",
			logo_tooltip = "Neovim",
			main_image = "language",
			client_id = "1157438221865717891",
			-- client_id = "1209645028670967868",
			log_level ="info",
			debounce_timeout = 10,
			blacklist = {},
			-- file_assets = {},
			show_time = true,
			global_timer = true,
			-- custom_distro = "Meuvim",

			editing_text = "Editing %s UwU",
			file_explorer_text = "Bwowsing files",
			git_commit_text = "Committing changes",
			plugin_manager_text = "Managing plugins",
			reading_text = "Weading %s",
			workspace_text = "Working on %s",
			line_number_text = "Line %s out of %s",
			terminal_text = "Using Terminal",
		},
	},
}
